package com.example.CareerPath_BE.entities;

import jakarta.persistence.*;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Questions generated by hbm2java
 */
@Entity
@Table(name = "questions")
public class Questions  implements java.io.Serializable {


     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     @Column(name = "question_id")
     private Integer questionId;

     @ManyToOne(fetch = FetchType.LAZY)
     @JoinColumn(name = "test_id")
     private Tests tests;

     @Column(name = "content")
     private String content;

     @Column(name = "dimension")
     private String dimension;

     @OneToMany(fetch = FetchType.LAZY, mappedBy = "questions")
     private Set<Choices> choiceses = new HashSet<>(0);

     @OneToMany(fetch = FetchType.LAZY, mappedBy = "questions")
     private Set<UserAnswers> userAnswerses = new HashSet<>(0);

     @OneToMany(fetch = FetchType.LAZY, mappedBy = "questions")
     private Set<QuestionFactors> questionFactorses = new HashSet<>(0);

    public Questions() {
    }

    public Questions(Tests tests, String content, String dimension, Set<Choices> choiceses, Set<UserAnswers> userAnswerses, Set<QuestionFactors> questionFactorses) {
       this.tests = tests;
       this.content = content;
       this.dimension = dimension;
       this.choiceses = choiceses;
       this.userAnswerses = userAnswerses;
       this.questionFactorses = questionFactorses;
    }
   
    public Integer getQuestionId() {
        return this.questionId;
    }
    
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }
    public Tests getTests() {
        return this.tests;
    }
    
    public void setTests(Tests tests) {
        this.tests = tests;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public String getDimension() {
        return this.dimension;
    }
    
    public void setDimension(String dimension) {
        this.dimension = dimension;
    }
    public Set<Choices> getChoiceses() {
        return this.choiceses;
    }
    
    public void setChoiceses(Set<Choices> choiceses) {
        this.choiceses = choiceses;
    }
    public Set<UserAnswers> getUserAnswerses() {
        return this.userAnswerses;
    }
    
    public void setUserAnswerses(Set<UserAnswers> userAnswerses) {
        this.userAnswerses = userAnswerses;
    }
    public Set<QuestionFactors> getQuestionFactorses() {
        return this.questionFactorses;
    }
    
    public void setQuestionFactorses(Set<QuestionFactors> questionFactorses) {
        this.questionFactorses = questionFactorses;
    }




}


